//
//  DevicePolicy.swift
//  SurveySyncEngineIOS
//
//

import Foundation

/// Categorizes the current network connection type to determine data usage constraints.
public enum NetworkType: String, Codable {
    // High-bandwidth, typically unmetered connection
    case wifi = "WIFI"
    
    // Cellular connection where the user may be charged for data (e.g., 4G/5G with a cap)
    case meteredCellular = "METERED_CELLULAR"
    
    // Cellular connection that is treated as unlimited
    case unmeteredCellular = "UNMETERED_CELLULAR"
    
    // Fallback when connectivity state cannot be determined
    case unknown = "UNKNOWN"
}

/// A configuration object generated by an evaluator to dictate how a sync session should behave.
public struct SyncPolicy {
    // Flag to determine if the SyncEngine is allowed to start processing the queue
    public let shouldSync: Bool
    
    // Human-readable explanation if shouldSync is false (e.g., "Low Battery")
    public let skipReason: String?
    
    /// The maximum cumulative byte count allowed for this specific session.
    /// Useful for preventing large video uploads on metered connections.
    public let maxBytesPerSession: Int64?
    
    /// Artificial pause (in milliseconds) between individual survey uploads to manage CPU/Battery thermals.
    public let itemDelay: Int64
    
    // The network state detected at the moment of evaluation
    public let networkType: NetworkType

    /// Memberwise initializer with sensible defaults for a standard sync session.
    public init(
        shouldSync: Bool,
        skipReason: String? = nil,
        maxBytesPerSession: Int64? = nil,
        itemDelay: Int64 = 0,
        networkType: NetworkType = .unknown
    ) {
        self.shouldSync = shouldSync
        self.skipReason = skipReason
        self.maxBytesPerSession = maxBytesPerSession
        self.itemDelay = itemDelay
        self.networkType = networkType
    }
}

/// A protocol defining the interface for any service that inspects device hardware states.
public protocol DevicePolicyEvaluator {
    /// Inspects system sensors (battery, storage, network) and returns a SyncPolicy.
    func evaluate() -> SyncPolicy
}
